### ISSUE TITLE
Sample submission files

### ISSUE THREAD

**Issue by qmaruf** [VisionLearningGroup/visda-2018-public#3]
Could you please provide a sample submission file? I am not sure how are you calculating the classification accuracy and writing those accuracy in files.

**Comment by MInner** [comment]
Hi. Are you talking about openset or detection problem?

**Comment by qmaruf** [comment]
openset. I am getting the following error though I have put source_results.txt and adaptation_results.txt in a zip file named ExMachina_submission.zip.

```
Traceback (most recent call last):
  File "/tmp/codalab/tmpot65Db/run/program/evaluate.py", line 130, in 
    classification_evaluation(truth_file, source_file, adaptation_file, output_file)
  File "/tmp/codalab/tmpot65Db/run/program/evaluate.py", line 42, in classification_evaluation
    with open(source_file) as f:
IOError: [Errno 2] No such file or directory: '/tmp/codalab/tmpot65Db/run/input/res/source_results.txt'
```

**Comment by nkaushik1** [comment]
Hi, we have uploaded a sample submission file [here](https://github.com/VisionLearningGroup/visda-2018-public/blob/master/openset/results/example_predictions.txt). I believe the submission error might have been because the submitted files were empty (or they appeared to be so when downloading from the server). Please try submitting again following this format and let us know if you have any issues!

**Comment by qmaruf** [comment]
Same error. Could you please provide a standalone zip folder as an example?

**Comment by nkaushik1** [comment]
I think I see the issue -- if you move the two files out of the subfolder in the zip file and delete the subfolder that should work!

**Comment by krumo** [comment]
Could you consider to provide a sample submission file for detection problem? Thanks in advance.
